### ISSUE TITLE
Run GUI version of VSFM

### ISSUE THREAD

**Issue by dbrgn** [ryanfb/docker_visualsfm#1]
Is it possible to run the VSFM GUI?

I tried this:

```
$ docker run -i -t -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY ryanfb/visualVisualSFM
```

But I get the following error messages:

```
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  32
  Current serial number in output stream:  31
```

Any ideas? It would be pretty cool if this would work.

**Comment by g19fanatic** [comment]
Looking at the base image's [requirements](https://hub.docker.com/r/tleyden5iwx/ubuntu-cuda/)

> Requirements
> Host must have nvida module and cuda libraries installed
> Docker container must have the nvidia devices passed in via --device flag

The default run command as given (and as given in the README) doesn't do this... Might be your issue...

**Comment by dbrgn** [comment]
That's possible. It's been a while though, so it isn't relevant to me anymore 🙂
